version: '2.4'

services:

  rp2paths:
    image: brsynth/${TOOL}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .env
    container_name: ${TOOL}
    restart: always

networks:
  default:
    name: ${TOOL}
