version: '2.4'

services:

  flask:
    image: brsynth/${TOOL}-rest:flask
    build:
      context: .
      dockerfile: flask.dockerfile
    env_file: .env
    container_name: ${TOOL}-flask
    restart: always
    volumes:
      - $PWD/../src:/home/src
      - $PWD/../efmtool:/home/efmtool
      - $PWD/../mnx-data:/home/mnx-data
      - $PWD/../examples:/home/examples
      - $PWD/app:/REST/app


networks:
  default:
    name: ${TOOL}
