version: '2.4'

services:

  rest:
    image: brsynth/${TOOL}-rest:${MODE}
    build:
      context: .
      dockerfile: ${MODE}.dockerfile
    env_file: .env
    container_name: ${TOOL}-rest
    restart: always
    volumes:
      - $PWD/../src:/home/src
      - $PWD/../efmtool:/home/efmtool
      - $PWD/../mnx-data:/home/mnx-data
      - $PWD/../examples:/home/examples
      - $PWD/app:/REST/app
      - $PWD/conf/supervisor.conf:/CONF/supervisor.conf


networks:
  default:
    name: ${TOOL}
