name: Test code

on:

  push:
    branches: [ master ]
    paths:
      - '**'
      - '!RELEASE.md'
      - '!LICENSE'
      - '!README.md'
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:

    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: rp2paths
        environment-file: environment.yaml
        auto-activate-base: false

    - name: Symlink data
      run: |
        ln -sf tests/data data

    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest --doctest-modules --verbose
